# 📊 Pandas Basics Tutorial
This notebook covers the basics of using **Pandas** for data analysis.
You'll learn how to:
- Load data
- Explore data
- Filter, update, and clean data
- Perform grouping, sorting, and exporting

Useful for quick **revision**.

In [1]:
import pandas as pd

## 📥 Reading a CSV File

In [2]:
df = pd.read_csv(r'C:\\Users\\Umer Azmi\\Downloads\\products.csv')
print('Print Function:')
print(df)

# `display()` is better inside Jupyter because it shows data in a table format
display(df)

Print Function:
    Index                                   Name                        Brand  \
0       1   Compact Printer Air Advanced Digital      Garner, Boyle and Flynn
1       2                                 Tablet                  Mueller Inc
2       3                   Smart Blender Cooker   Lawson, Keller and Winters
3       4           Advanced Router Rechargeable           Gallagher and Sons
4       5           Portable Mouse Monitor Phone                    Irwin LLC
..    ...                                    ...                          ...
95     96                                 Router                 Atkinson Inc
96     97     Fast Thermostat Microphone Scooter                     Shea Ltd
97     98  Eco Heater Toaster Stove Silent Sense                     West Ltd
98     99               Clean Blender Scale Lite     Bell, Gamble and Barrett
99    100                             Smart Lamp  Hebert, Hughes and Trujillo

                  Category  Price  Stock        Color         Size  \
0       Books & Stationery    265    774  ForestGreen        Large
1         Shoes & Footwear    502     81        Black      8x10 in
2       Kitchen Appliances    227    726    SlateGray           XS
3       Kitchen Appliances    121    896    PaleGreen            L
4           Kids' Clothing      1    925     SeaShell   100x200 mm
..                     ...    ...    ...          ...          ...
95     Laptops & Computers    375    703    Gainsboro      8x10 in
96  Beauty & Personal Care    289    727        White  Extra Large
97       Cleaning Supplies    232    998      OldLace        Small
98        Camping & Hiking    241    391   Aquamarine       5x7 in
99          Bedding & Bath     71    518        Brown       Medium

     Availability
0       pre_order
1        in_stock
2        in_stock
3    discontinued
4    discontinued
..            ...
95  limited_stock
96      backorder
97  limited_stock
98  limited_stock
99  limited_stock

[100 rows x 9 columns]

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
0,1,Compact Printer Air Advanced Digital,"Garner, Boyle and Flynn",Books & Stationery,265,774,ForestGreen,Large,pre_order
1,2,Tablet,Mueller Inc,Shoes & Footwear,502,81,Black,8x10 in,in_stock
2,3,Smart Blender Cooker,"Lawson, Keller and Winters",Kitchen Appliances,227,726,SlateGray,XS,in_stock
3,4,Advanced Router Rechargeable,Gallagher and Sons,Kitchen Appliances,121,896,PaleGreen,L,discontinued
4,5,Portable Mouse Monitor Phone,Irwin LLC,Kids' Clothing,1,925,SeaShell,100x200 mm,discontinued
...,...,...,...,...,...,...,...,...,...
95,96,Router,Atkinson Inc,Laptops & Computers,375,703,Gainsboro,8x10 in,limited_stock
96,97,Fast Thermostat Microphone Scooter,Shea Ltd,Beauty & Personal Care,289,727,White,Extra Large,backorder
97,98,Eco Heater Toaster Stove Silent Sense,West Ltd,Cleaning Supplies,232,998,OldLace,Small,limited_stock
98,99,Clean Blender Scale Lite,"Bell, Gamble and Barrett",Camping & Hiking,241,391,Aquamarine,5x7 in,limited_stock
99,100,Smart Lamp,"Hebert, Hughes and Trujillo",Bedding & Bath,71,518,Brown,Medium,limited_stock

## 👀 Viewing Data

In [4]:
# Shows first 5 rows
display(df.head())

# Shows last 5 rows
df.tail()

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
0,1,Compact Printer Air Advanced Digital,"Garner, Boyle and Flynn",Books & Stationery,265,774,ForestGreen,Large,pre_order
1,2,Tablet,Mueller Inc,Shoes & Footwear,502,81,Black,8x10 in,in_stock
2,3,Smart Blender Cooker,"Lawson, Keller and Winters",Kitchen Appliances,227,726,SlateGray,XS,in_stock
3,4,Advanced Router Rechargeable,Gallagher and Sons,Kitchen Appliances,121,896,PaleGreen,L,discontinued
4,5,Portable Mouse Monitor Phone,Irwin LLC,Kids' Clothing,1,925,SeaShell,100x200 mm,discontinued

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
95,96,Router,Atkinson Inc,Laptops & Computers,375,703,Gainsboro,8x10 in,limited_stock
96,97,Fast Thermostat Microphone Scooter,Shea Ltd,Beauty & Personal Care,289,727,White,Extra Large,backorder
97,98,Eco Heater Toaster Stove Silent Sense,West Ltd,Cleaning Supplies,232,998,OldLace,Small,limited_stock
98,99,Clean Blender Scale Lite,"Bell, Gamble and Barrett",Camping & Hiking,241,391,Aquamarine,5x7 in,limited_stock
99,100,Smart Lamp,"Hebert, Hughes and Trujillo",Bedding & Bath,71,518,Brown,Medium,limited_stock

## 📝 Dataset Info & Summary

In [5]:
display(df.info())  # General info about dataset
df.describe()  # Statistical summary for numeric columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         100 non-null    int64
 1   Name          100 non-null    object
 2   Brand         100 non-null    object
 3   Category      100 non-null    object
 4   Price         100 non-null    int64
 5   Stock         100 non-null    int64
 6   Color         100 non-null    object
 7   Size          100 non-null    object
 8   Availability  100 non-null    object
dtypes: int64(3), object(6)
memory usage: 7.2+ KB

None

            Index      Price       Stock
count  100.000000  100.00000  100.000000
mean    50.500000  451.19000  545.710000
std     29.011492  281.60911  266.716863
min      1.000000    1.00000   10.000000
25%     25.750000  230.75000  347.500000
50%     50.500000  407.50000  575.500000
75%     75.250000  679.00000  749.250000
max    100.000000  999.00000  998.000000

## 🔎 Columns and Index

In [6]:
display(df.columns)  # List of all columns
display(df.index)    # Index range of rows

Index(['Index', 'Name', 'Brand', 'Category', 'Price', 'Stock', 'Color', 'Size',
       'Availability'],
      dtype='object')

RangeIndex(start=0, stop=100, step=1)

## 🎯 Selecting Columns

In [7]:
display(df['Name'].head())   # Single column = Series
print(f'Total Entries: {len(df["Name"])}')

display(df[['Name','Brand']])   # Multiple columns = DataFrame

0    Compact Printer Air Advanced Digital
1                                  Tablet
2                    Smart Blender Cooker
3            Advanced Router Rechargeable
4            Portable Mouse Monitor Phone
Name: Name, dtype: object

Total Entries: 100

                                     Name                        Brand
0    Compact Printer Air Advanced Digital      Garner, Boyle and Flynn
1                                  Tablet                  Mueller Inc
2                    Smart Blender Cooker   Lawson, Keller and Winters
3            Advanced Router Rechargeable           Gallagher and Sons
4            Portable Mouse Monitor Phone                    Irwin LLC
..                                    ...                          ...
95                                 Router                 Atkinson Inc
96     Fast Thermostat Microphone Scooter                     Shea Ltd
97  Eco Heater Toaster Stove Silent Sense                     West Ltd
98               Clean Blender Scale Lite     Bell, Gamble and Barrett
99                             Smart Lamp  Hebert, Hughes and Trujillo

[100 rows x 2 columns]

## 📌 Selecting Rows with `iloc`

In [9]:
display(df.iloc[0])   # First row

display(df.iloc[0][0])   # First row, first column
df.iloc[0]['Stock']      # Specific column in first row

Index                                              1
Name            Compact Printer Air Advanced Digital
Brand                        Garner, Boyle and Flynn
Category                          Books & Stationery
Price                                            265
Stock                                            774
Color                                    ForestGreen
Size                                           Large
Availability                               pre_order
Name: 0, dtype: object

C:\Users\Umer Azmi\AppData\Local\Temp\ipykernel_18428\2675584295.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  display(df.iloc[0][0])   # First row, first column

1

774

## 🔍 Filtering Data

In [12]:
display(df[df['Category'] == "Men's Clothing"])   # Simple filter

display(df[(df['Price'] >= 500) & (df['Availability'] == 'in_stock')])  # AND condition

display(df[(df['Color'] == 'Black') | (df['Category'] == "Men's Clothing")])  # OR condition

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
58,59,Oven Speaker Fan,Schwartz Ltd,Men's Clothing,489,423,GoldenRod,Small,pre_order
60,61,Smart Webcam Projector Lock,Stokes Inc,Men's Clothing,440,973,SteelBlue,Medium,in_stock

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
1,2,Tablet,Mueller Inc,Shoes & Footwear,502,81,Black,8x10 in,in_stock
28,29,Clock Brush,Larson-Spence,Furniture,985,180,SaddleBrown,Extra Large,in_stock
50,51,Mini Fridge Camera,Decker and Sons,Fitness Equipment,777,832,PaleGoldenRod,Extra Large,in_stock
51,52,Rechargeable Tablet Plus Portable Mini,Mooney-Gonzales,Fragrances,820,535,Cyan,100x200 mm,in_stock
53,54,Wireless Light Toaster Lite Touch Eco,Singleton PLC,Bedding & Bath,791,827,Fuchsia,50x70 cm,in_stock
59,60,Automatic Speaker Router Lamp Prime,"Sexton, Dickerson and Blair",Grooming Tools,621,667,FireBrick,5x7 in,in_stock
66,67,Mini Charger Lock Oven Sense Sense,"Burton, Gross and Giles",Haircare,750,623,Olive,12x18 in,in_stock
72,73,Compact Thermostat Oven,Hull Inc,Home & Kitchen,685,747,SaddleBrown,30x40 cm,in_stock
75,76,Rechargeable Webcam Dock Heater,Kennedy-Gordon,Cycling,800,151,Brown,XXL,in_stock
91,92,Portable Scooter Wireless Digital,Bauer Inc,Cameras & Accessories,519,495,DeepSkyBlue,Large,in_stock

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
1,2,Tablet,Mueller Inc,Shoes & Footwear,502,81,Black,8x10 in,in_stock
58,59,Oven Speaker Fan,Schwartz Ltd,Men's Clothing,489,423,GoldenRod,Small,pre_order
60,61,Smart Webcam Projector Lock,Stokes Inc,Men's Clothing,440,973,SteelBlue,Medium,in_stock
92,93,Fridge Cooker,Jackson Group,Furniture,393,499,Black,Small,in_stock

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
1,2,Tablet,Mueller Inc,Shoes & Footwear,502,81,Black,8x10 in,in_stock
18,19,Eco Freezer Powerbank Watch,"Pruitt, Higgins and Barnett",Cleaning Supplies,340,618,Cyan,S,limited_stock
51,52,Rechargeable Tablet Plus Portable Mini,Mooney-Gonzales,Fragrances,820,535,Cyan,100x200 mm,in_stock
65,66,Treadmill,"Frost, Christensen and Burnett",Women's Clothing,731,744,Cyan,5x7 in,out_of_stock
84,85,Fast Keyboard,Lewis Ltd,Camping & Hiking,998,10,Cyan,50x70 cm,limited_stock
92,93,Fridge Cooker,Jackson Group,Furniture,393,499,Black,Small,in_stock

## ✨ String Functions in Filters

In [13]:
display(df[df['Category'].str.lower().str.startswith('laptop')])
display(df[df['Category'].str.lower().str.endswith('clothing')])
df[df['Category'].str.contains('clothing', case=False)]

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
6,7,Ultra Projector Oven Thermostat Prime Advanced,"Mccoy, Waters and Rose",Laptops & Computers,68,870,Purple,S,discontinued
89,90,Digital Trimmer,Christian-Tanner,Laptops & Computers,541,488,SteelBlue,M,pre_order
95,96,Router,Atkinson Inc,Laptops & Computers,375,703,Gainsboro,8x10 in,limited_stock

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
4,5,Portable Mouse Monitor Phone,Irwin LLC,Kids' Clothing,1,925,SeaShell,100x200 mm,discontinued
20,21,Portable Camera Plus Air Ultra,Wang-Valenzuela,Women's Clothing,197,163,Magenta,L,in_stock
29,30,Keyboard Toaster Monitor,Bonilla-Spears,Kids' Clothing,576,988,DarkSlateGray,L,pre_order
33,34,Automatic Brush Fast Eco,Newman Ltd,Kids' Clothing,407,285,SeaGreen,8x10 in,out_of_stock
35,36,Smart Phone Scooter Clean,Marshall-Dougherty,Women's Clothing,635,727,MediumVioletRed,10x10 cm,backorder
37,38,Ultra Dock Trimmer Automatic Edge,Barnes-Glass,Kids' Clothing,640,780,LightBlue,5x7 in,discontinued
57,58,Portable Scale Speaker Powerbank Clean,Morris LLC,Women's Clothing,689,332,PowderBlue,Small,backorder
58,59,Oven Speaker Fan,Schwartz Ltd,Men's Clothing,489,423,GoldenRod,Small,pre_order
60,61,Smart Webcam Projector Lock,Stokes Inc,Men's Clothing,440,973,SteelBlue,Medium,in_stock
65,66,Treadmill,"Frost, Christensen and Burnett",Women's Clothing,731,744,Cyan,5x7 in,out_of_stock
76,77,Clean Toaster Oven Air Touch,Olsen-Sawyer,Kids' Clothing,365,71,LimeGreen,Medium,pre_order
85,86,Ultra Mixer Toaster Toaster Smart,Galloway and Sons,Women's Clothing,342,221,Tomato,S,pre_order

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
4,5,Portable Mouse Monitor Phone,Irwin LLC,Kids' Clothing,1,925,SeaShell,100x200 mm,discontinued
20,21,Portable Camera Plus Air Ultra,Wang-Valenzuela,Women's Clothing,197,163,Magenta,L,in_stock
27,28,Wireless Webcam Stove Grill,Henry Group,Clothing & Apparel,858,912,LightSalmon,50x70 cm,limited_stock
29,30,Keyboard Toaster Monitor,Bonilla-Spears,Kids' Clothing,576,988,DarkSlateGray,L,pre_order
33,34,Automatic Brush Fast Eco,Newman Ltd,Kids' Clothing,407,285,SeaGreen,8x10 in,out_of_stock
35,36,Smart Phone Scooter Clean,Marshall-Dougherty,Women's Clothing,635,727,MediumVioletRed,10x10 cm,backorder
37,38,Ultra Dock Trimmer Automatic Edge,Barnes-Glass,Kids' Clothing,640,780,LightBlue,5x7 in,discontinued
57,58,Portable Scale Speaker Powerbank Clean,Morris LLC,Women's Clothing,689,332,PowderBlue,Small,backorder
58,59,Oven Speaker Fan,Schwartz Ltd,Men's Clothing,489,423,GoldenRod,Small,pre_order
60,61,Smart Webcam Projector Lock,Stokes Inc,Men's Clothing,440,973,SteelBlue,Medium,in_stock
65,66,Treadmill,"Frost, Christensen and Burnett",Women's Clothing,731,744,Cyan,5x7 in,out_of_stock
76,77,Clean Toaster Oven Air Touch,Olsen-Sawyer,Kids' Clothing,365,71,LimeGreen,Medium,pre_order
85,86,Ultra Mixer Toaster Toaster Smart,Galloway and Sons,Women's Clothing,342,221,Tomato,S,pre_order

## 📋 Checking Membership with `isin`

In [14]:
display(df[df['Size'].str.lower().isin(['l', 'large'])])
display(df[~df['Size'].str.lower().isin(['l', 'large'])])  # ~ = NOT

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
0,1,Compact Printer Air Advanced Digital,"Garner, Boyle and Flynn",Books & Stationery,265,774,ForestGreen,Large,pre_order
3,4,Advanced Router Rechargeable,Gallagher and Sons,Kitchen Appliances,121,896,PaleGreen,L,discontinued
12,13,Heater Radio,Delgado-Blackwell,Cycling,689,156,Orange,L,pre_order
20,21,Portable Camera Plus Air Ultra,Wang-Valenzuela,Women's Clothing,197,163,Magenta,L,in_stock
22,23,Rechargeable Lamp Speakerphone Headphones,"Gallegos, Osborne and Carpenter",Skincare,664,577,DarkBlue,L,pre_order
23,24,Mini Scooter Microphone,"Douglas, Thornton and Soto",Grooming Tools,784,510,DimGray,L,backorder
29,30,Keyboard Toaster Monitor,Bonilla-Spears,Kids' Clothing,576,988,DarkSlateGray,L,pre_order
30,31,Silent Printer Fan Shaver,Love LLC,Sports & Outdoors,102,669,MediumSpringGreen,L,limited_stock
46,47,Portable Powerbank X Air,Hanson-Schultz,Camping & Hiking,599,263,Moccasin,Large,discontinued
54,55,Scooter,Rivas Group,Cameras & Accessories,370,601,DarkOrchid,L,backorder
73,74,Wireless Watch Tablet Printer Automatic Eco Sense,Fleming Inc,Smartwatches,59,169,Sienna,Large,out_of_stock
78,79,Portable Kettle,Sampson-Leon,Home & Kitchen,50,413,MediumAquaMarine,L,pre_order
88,89,Fast Vacuum Cooler,Blair-Russell,Sports & Outdoors,307,320,LightSalmon,L,limited_stock
91,92,Portable Scooter Wireless Digital,Bauer Inc,Cameras & Accessories,519,495,DeepSkyBlue,Large,in_stock

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
1,2,Tablet,Mueller Inc,Shoes & Footwear,502,81,Black,8x10 in,in_stock
2,3,Smart Blender Cooker,"Lawson, Keller and Winters",Kitchen Appliances,227,726,SlateGray,XS,in_stock
4,5,Portable Mouse Monitor Phone,Irwin LLC,Kids' Clothing,1,925,SeaShell,100x200 mm,discontinued
5,6,Radio,"Benjamin, Nelson and Hancock",Skincare,426,549,CornflowerBlue,30x40 cm,pre_order
6,7,Ultra Projector Oven Thermostat Prime Advanced,"Mccoy, Waters and Rose",Laptops & Computers,68,870,Purple,S,discontinued
...,...,...,...,...,...,...,...,...,...
95,96,Router,Atkinson Inc,Laptops & Computers,375,703,Gainsboro,8x10 in,limited_stock
96,97,Fast Thermostat Microphone Scooter,Shea Ltd,Beauty & Personal Care,289,727,White,Extra Large,backorder
97,98,Eco Heater Toaster Stove Silent Sense,West Ltd,Cleaning Supplies,232,998,OldLace,Small,limited_stock
98,99,Clean Blender Scale Lite,"Bell, Gamble and Barrett",Camping & Hiking,241,391,Aquamarine,5x7 in,limited_stock
99,100,Smart Lamp,"Hebert, Hughes and Trujillo",Bedding & Bath,71,518,Brown,Medium,limited_stock

## ✏️ Updating Values

In [16]:
df.loc[df['Name'] == 'Tablet', 'Size'] = 'M'
display(df[df['Name'] == 'Tablet'])

,Index,Name,Brand,Category,Price,Stock,Color,Size,Availability
1,2,Tablet,Mueller Inc,Shoes & Footwear,502,81,Black,M,in_stock
52,53,Tablet,"Blake, Weiss and Montgomery",Beauty & Personal Care,408,922,Chocolate,M,backorder

## ❌ Dropping Rows

In [ ]:
df = df.drop(99)  # Drops row at index 99
df.tail()

## 🚿 Handling Missing Values (NaN)

In [17]:
df = df.dropna()  # Removes rows with missing values

df.fillna({'Size': 'One Size Fits All'}, inplace=True)  # Fill missing values

## 🏷️ Renaming Columns

In [ ]:
df.rename(columns={'Index': 'SR Number'}, inplace=True)

## 🔢 Value Counts

In [18]:
df['Size'].value_counts()

Size
L              10
Extra Large     9
5x7 in          9
S               8
8x10 in         8
Medium          6
10x10 cm        6
M               6
XXL             6
XL              5
Small           5
50x70 cm        5
Large           4
12x18 in        4
30x40 cm        3
100x200 mm      3
XS              3
Name: count, dtype: int64

## 📊 Grouping & Sorting

In [ ]:
display(df.groupby('Availability')['Price'].sum())  # Group by Availability

df.sort_values('Price', ascending=False).head(10)   # Top 10 expensive items

## 💾 Saving to CSV

In [ ]:
df.to_csv('newfile.csv', index=False)  # Save changes to a new CSV file